/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as createImage from "../createImage.js";
import type * as createSketch from "../createSketch.js";
import type * as createUser from "../createUser.js";
import type * as http from "../http.js";
import type * as stripe from "../stripe.js";
import type * as todo from "../todo.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  createImage: typeof createImage;
  createSketch: typeof createSketch;
  createUser: typeof createUser;
  http: typeof http;
  stripe: typeof stripe;
  todo: typeof todo;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
