import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ConvexClientProvider } from "./ConvexClientProvider";
import DataContextProvider from "./Context/Provider";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <DataContextProvider>
      <Navbar/>
      <ConvexClientProvider>
       {children}
      </ConvexClientProvider>
      </DataContextProvider>
      </body>
    </html>
  );
}
